### ISSUE TITLE
typeDefs and Resolvers

### ISSUE THREAD

**Issue by MariaFernandaMarroquin** [1alyciaoliveira/JobJorney#15]

**Comment by MariaFernandaMarroquin** [comment]
server side - typedefs and resolvers created. Pending: token and token function in resolvers (adduser, login mutations).

**Comment by 1alyciaoliveira** [comment]
@MariaFernandaMarroquin please, merge branch with master, so I can add token function.

**Comment by MariaFernandaMarroquin** [comment]
typeDefs updated. Pending: token linked in resolvers. Aly will work on a new branch.
